{
 "title": "Hatch@FIT",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Hatch@FIT Dashboard\n\nVýrazne upozornujeme, že pracujete z citlivými osobnými údajmi!"
   }
  },
  {
   "title": "Najviac vyuzivane IZO",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "hatchafit",
     "rawSql": "SELECT\n  school_izo,\n  COUNT(*) AS count\nFROM\n  hatchafit.user\nGROUP BY\n  school_izo\nORDER BY\n  count DESC;\n"
    }
   ]
  },
  {
   "title": "Currently registered users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hatchafit",
     "rawSql": "SELECT COUNT(*) FROM hatchafit.user LIMIT 50 "
    }
   ]
  },
  {
   "title": "All user view",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "hatchafit",
     "rawSql": "SELECT name, surname, school, current_pfp_background, current_pfp_duck, current_pfp_face, current_pfp_foreground, current_pfp_head, current_pfp_left, current_pfp_neck, current_pfp_right FROM hatchafit.user LIMIT 50 "
    }
   ]
  }
 ]
}